### ISSUE TITLE
Create Docker Image that can be deployed as droplet

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_webapp#18]
Create a docker file so that we can build a docker image that contains this website.

**Comment by chenry** [comment]
@mccrackend let me know the results of this.  I would like to know if / when this is done, can we move forward with getting it deployed out to DigitalOcean.

**Comment by mccrackend** [comment]
I think I've got it. I need to work with Mikita on getting it ready for the
deployment piece.
